apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
      - name: ecom-app
        image: anfastk/laptix-ecom:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: ecommerce-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5