apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - laptix.ddns.net
      secretName: laptix-tls
  rules:
    - host: laptix.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecom-app-service
                port:
                  number: 80