apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - laptix.ddns.net
    secretName: laptix-tls
  rules:
  - host: laptix.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecom-app-service
            port:
              number: 80