apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod  
spec:
  rules:
  - host: laptix.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecom-app-service
            port:
              number: 80
  tls:   
  - hosts:
    - laptix.ddns.net
    secretName: tls-laptix-ddns-net
