apiVersion: v1
kind: Service
metadata:
  name: ecom-app-service
spec:
  selector:
    app: ecom-app
  ports:
    - protocol: TCP
      port: 80         # expose port 80 inside cluster
      targetPort: 8080 # your app listens on 8080
  type: ClusterIP    # internal service only, no NodePort
