apiVersion: v1
kind: Service
metadata:
  name: ecom-app-service
spec:
  type: LoadBalancer         # Use LoadBalancer for external access
  selector:
    app: ecom-app
  ports:
    - port: 80
      targetPort: 8080
